swagger: '2.0'
info:
  title: YourApp
  description: 'your App'
  version: 1.0.0
host: 'localhost:5000'
basePath: /service/
consumes:
  - application/json
produces:
  - application/json

paths:
  /server/time:
    get:
      tags:
        - hours
      summary: the local server time
      x-swagger-router-controller: server.time
      responses:
        '200':
          description: the local server time answer

  /about:
    get:
      tags:
        - about
      summary: About this API
      x-swagger-router-controller: about.about
      parameters:
        - name: name
          in: query
          required: false
          type: string
      responses:
        '200':
          description: About
          schema:
            $ref: '#/definitions/about'

  /search:
    get:
      tags:
        - search
      summary: modulo de cotizacion
      x-swagger-router-controller: search.search
      parameters:
        - name: email
          in: query
          required: true
          type: string
        - name: zonaDestino
          in: query
          required: true
          type: string
        - name: fechaDesde
          in: query
          required: true
          type: string
          format: date
        - name: fechaHasta
          in: query
          required: true
          type: string
          format: date
        - name: adultos
          in: query
          required: true
          type: integer
      responses:
        '200':
          description: About
          schema:
            $ref: '#/definitions/about'


definitions:
  about:
    type: object
    properties:
      IdProducto:
        type: string
      NombreProducto:
        type: string
      Precio:
        type: string
